name: "Tag on Pull Request merge"
# Workflow 1
# This workflow is triggered when a pull request for branch main is closed and merged.
# Creates a new tag on the merge commit.

on:
  # Should trigger only when a Pull Request is Closed
  # (the action will not create the Tag if the Pull Request is discarded - closed without merge)
  pull_request:
    types:
      - closed
    branches:
      - main
      - test/tag

jobs:
  tag-on-pr-merge:
    name: Tag on Pull Request merge
    runs-on: ubuntu-latest
    # This 'if' condition is important for ensuring the workflow only runs for merged PRs
    #  (avoid running when a PR is discarded - closed without merging)
    if: github.event.pull_request.merged == true
    steps:
      # Fetch the tag from the PR, and push it if detected
      - name: Tag on PR merge
        id: tag-on-pr-merge
        uses: David-Lor/action-tag-on-pr-merge@main
        with:
          push-tag: true
      - name: Print fetched tag
        run: echo "${{ steps.tag-on-pr-merge.outputs.tag }}"

      # Trigger the Release workflow, since an action triggered from a workflow (the creation of the new tag) cannot trigger another workflow.
      #  Send the detected tag on payload.
      - name: Trigger Release workflow
        uses: peter-evans/repository-dispatch@c73dcc42429d4220d60b2b8daf3cee190a131129
        if: steps.tag-on-pr-merge.outputs.tag
        with:
          token: ${{ secrets.PAT }}  # Requires creating a Personal Access Token, with repo or public_repo scope
          repository: David-Lor/Github-Actions-PR-Tag-Release  # Change with your repository
          event-type: from_tag
          client-payload: |-
            {
              "tag": "${{ steps.tag-on-pr-merge.outputs.tag }}"
            }
